import os
import sys
import pandas as pd
from Bio.PDB import MMCIFParser
from Bio.PDB.Polypeptide import PPBuilder

_mmcif_parser = MMCIFParser(QUIET=True)
_ppb = PPBuilder()

def get_chain_sequences(cif_path):
    structure = _mmcif_parser.get_structure('s', cif_path)
    sequences = {}
    for model in structure:
        for chain in model:
            seq = ''.join(str(pp.get_sequence()) for pp in _ppb.build_peptides(chain))
            if seq:
                sequences[chain.id] = seq
        break
    return sequences

def calculate_ipsae(
    pae_file_path,
    structure_file_path,
    pae_cutoff=15.0,
    dist_cutoff=15.0,
):
    """
    Calculate ipSAE scores, correctly capturing both directions to find min/max.
    """
    # Run the external ipsae script
    # Ensure ipsae.py is in the same directory as this script
    os.system(f"python3 ipsae.py {pae_file_path} {structure_file_path} {pae_cutoff} {dist_cutoff}")

    # The output filename generated by ipsae.py
    result_file = structure_file_path.replace('.cif', f'_{int(pae_cutoff)}_{int(dist_cutoff)}.txt')
    
    if not os.path.exists(result_file):
        raise FileNotFoundError(f"Expected output file {result_file} was not created.")

    print(f"Reading results from {result_file}")
    df = pd.read_csv(result_file)
    results = {}

    # 1. Process each unique chain pair found in the 'max' rows
    for i, row in df[df.Type=="max"].iterrows():
        c1, c2 = row['Chn1'], row['Chn2']
        chainpair = f"{c1}-{c2}"

        # Store the 'max' values (the best-case direction)
        results[chainpair] = {
            "max": {**{col: row[col] for col in df.columns[5:-1]}}
        }

        # 2. FIXED MASK: Look for BOTH directions (A-B and B-A) 
        # to find the true minimum of the asymmetric scores.
        mask = (
            ((df['Chn1'] == c1) & (df['Chn2'] == c2)) | 
            ((df['Chn1'] == c2) & (df['Chn2'] == c1))
        ) & (df['Type'] == "asym")
        
        # 3. Calculate the minimum values across those rows
        if not df[mask].empty:
            min_vals = df[mask][df.columns[5:-1]].min()
            results[chainpair]["min"] = min_vals.to_dict()
        else:
            # Fallback if asym rows aren't labeled as expected
            results[chainpair]["min"] = results[chainpair]["max"]

    return results

# --- MAIN EXECUTION BLOCK ---

if len(sys.argv) < 2:
    print("Usage: python boltzipsae.py <boltz_results_dir>")
    sys.exit(1)

predictions_dir = os.path.join(sys.argv[1], "predictions")
job_folders = [f.path for f in os.scandir(predictions_dir) if f.is_dir()]
all_rows = []

for folder in job_folders:
    folder_name = os.path.basename(folder)
    
    # Path logic: folder/folder_model_0.cif
    cif_file = os.path.join(folder, f"{folder_name}_model_0.cif")
    pae_file = os.path.join(folder, f"pae_{folder_name}_model_0.npz")
    
    print(f"\n>>> Processing: {folder_name}")
    
    if os.path.exists(cif_file) and os.path.exists(pae_file):
        try:
            scores = calculate_ipsae(pae_file, cif_file)
            chain_seqs = get_chain_sequences(cif_file)

            for pair, data in scores.items():
                # Create a row containing both MAX and MIN metrics
                row = {"Job": folder_name, "Chain_Pair": pair}

                # Add binder sequence (the non-A chain in the pair)
                binder_chain = next((c for c in pair.split('-') if c != 'A'), None)
                row["Binder_Sequence"] = chain_seqs.get(binder_chain, "") if binder_chain else ""

                # Prefixing keys so you can tell max from min in the CSV
                row.update({f"max_{k}": v for k, v in data["max"].items()})
                row.update({f"min_{k}": v for k, v in data["min"].items()})

                all_rows.append(row)
                
        except Exception as e:
            print(f"Error processing {folder_name}: {e}")
    else:
        print(f"Files missing in {folder}. Check naming convention.")

# 2. Save Comprehensive Summary
if all_rows:
    summary_df = pd.DataFrame(all_rows)
    summary_df.to_csv("ipsae_results_full.csv", index=False)
    print("\n[Success] Full results saved to ipsae_results_full.csv")

    # 3. Create a filtered "Target-Only" Min Report
    # Filter for pairs involving Chain A (assuming A is your target)
    target_df = summary_df[summary_df['Chain_Pair'].str.contains('A')]
    
    if not target_df.empty:
        # Get the row with the absolute lowest min_ipSAE per Job
        idx = target_df.groupby('Job')['max_ipSAE'].idxmin()
        min_report = target_df.loc[idx].copy()
        
        min_report.to_csv("ipsae_min_report.csv", index=False)
        print("[Success] Worst-case (Min) report saved to ipsae_min_report.csv")
else:
    print("No results were generated. Check your 'predictions' folder structure.")